### ISSUE TITLE
The code for "memory.pt"

### ISSUE THREAD

**Issue by lemon234071** [simplc/WCN-BERT#2]
Thank you for your nice work, may i get the code to process the raw data and generate the "memory.pt"?

**Comment by lemon234071** [comment]
And what are the "parent" and "sibs" for ?

**Comment by simplc** [comment]
We have updated the repo, and you can check the preprocessing code in `helpers/process_dstc2_data.py`. If you want to run the code, please download the DSTC2 data and follow the instructions in the README file. 

> Thank you for your nice work, may i get the code to process the raw data and generate the "memory.pt"?

**Comment by simplc** [comment]
We initially want to encode the system acts with the help of their relationships in the format of a graph (actaully it is a tree). E.g., for a system act, `inform-pricerange-cheap`, we first obtain the system act sequence `inform price range cheap`, then we can define the tree-like relationship between those tokens:
- the parent of `price` and `range` is `inform`; the parent of `cheap` is `price` (only one parent for simplicity).
- the sibling of `range` is `price`.
By doing this, we can determine the relationship between them, and we can further define something like attention masks as restrictions. You can find the details in function `process_sys_acts()` in `helpers/process_dstc2_data.py`.

BUT this relationship is not included both in this repo and in our paper. 

> And what are the "parent" and "sibs" for ?

**Comment by lemon234071** [comment]
Thank you very very much! you are so nice!
